// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY8ccUEAAn2Udn73JCQ8kvPwJ_XmIu6xw',
    appId: '1:820135506142:web:c01d1dd049efc49434d24f',
    messagingSenderId: '820135506142',
    projectId: 'sert-firebase',
    authDomain: 'sert-firebase.firebaseapp.com',
    storageBucket: 'sert-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcr7ZbRQqwont58KLYnkcUumguzUjWx3I',
    appId: '1:820135506142:android:e3916b0f7e23e41f34d24f',
    messagingSenderId: '820135506142',
    projectId: 'sert-firebase',
    storageBucket: 'sert-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWujWWN8S_mqTT9n1nnl5CKHg95MpUAi0',
    appId: '1:820135506142:ios:15704dbd374f808834d24f',
    messagingSenderId: '820135506142',
    projectId: 'sert-firebase',
    storageBucket: 'sert-firebase.appspot.com',
    iosClientId: '820135506142-coq9ul33eocc31mo5oantsanhhvhnk4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.sertf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWujWWN8S_mqTT9n1nnl5CKHg95MpUAi0',
    appId: '1:820135506142:ios:15704dbd374f808834d24f',
    messagingSenderId: '820135506142',
    projectId: 'sert-firebase',
    storageBucket: 'sert-firebase.appspot.com',
    iosClientId: '820135506142-coq9ul33eocc31mo5oantsanhhvhnk4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.sertf',
  );
}
